MvcCoreProceduresEF/Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("DOCTOR")]
    public class Doctor
    {
        [Key]
        [Column("DOCTOR_NO")]
        public int DoctorNo { get; set; }

        [Column("HOSPITAL_COD")]
        public int HospitalCod { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("ESPECIALIDAD")]
        public string Especialidad { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

MvcCoreProceduresEF/Models/Enfermo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("ENFERMO")]
    public class Enfermo
    {
        [Key]
        [Column("INSCRIPCION")]
        public string Inscripcion { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("DIRECCION")]
        public string Direccion { get; set; }

        [Column("FECHA_NAC")]
        public DateTime FechaNac { get; set; }

        [Column("S")]
        public string Sexo { get; set; }

        [Column("NSS")]
        public string NSS { get; set; }
    }
}

MvcCoreProceduresEF/Models/ErrorViewModel.cs
namespace MvcCoreProceduresEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreProceduresEF/Models/Trabajador.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("V_TRABAJADORES")]
    public class Trabajador
    {
        [Key]
        [Column("IDTRABAJADOR")]
        public int IdTrabajador { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

MvcCoreProceduresEF/Models/TrabajadoresModel.cs
namespace MvcCoreProceduresEF.Models
{
    public class TrabajadoresModel
    {
        public List<Trabajador> Trabajadores { get; set; }
        public int Personas { get; set; }
        public int Suma { get; set; }
        public int Media { get; set; }
    }
}

MvcCoreProceduresEF/Models/VistaEmpleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("V_EMPLEADOS_DEPARTAMENTOS")]
    public class VistaEmpleado
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }

        [Column("DEPARTAMENTO")]
        public string Departamento { get; set; }

        [Column("LOCALIDAD")]
        public string Localidad { get; set; }
    }
}

MvcCoreProceduresEF/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<VistaEmpleado> vistaEmpleados = await repo.GetVistaEmpleadosAsync();
            return View(vistaEmpleados);
        }
    }
}

MvcCoreProceduresEF/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class EnfermosController : Controller
    {
        private RepositoryEnfermos repo;

        public EnfermosController(RepositoryEnfermos repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Enfermo> enfermos = await repo.GetEnfermosAsync();
            return View(enfermos);
        }

        public async Task<IActionResult> Details(string inscripcion)
        {
            Enfermo enfermo = await repo.FindEnfermoAsync(inscripcion);
            return View(enfermo);
        }

        public async Task<IActionResult> Delete(string inscripcion)
        {
            await repo.DeleteEnfermoRawAsync(inscripcion);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Insert()
        {
            return View();
        }

        public async Task<IActionResult> SubirSalario()
        {
            List<string> especialidades = await repo.GetEspecialidadesAsync();
            ViewData["Especialidades"] = especialidades;
            return View();
        }

        public async Task<IActionResult> SubirSalarioEF()
        {
            List<string> especialidades = await repo.GetEspecialidadesAsync();
            ViewData["Especialidades"] = especialidades;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(string apellido, string direccion, string sexo, string nss)
        {
            await repo.InsertEnfermoAsync(apellido, direccion, DateTime.Now, sexo, nss);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SubirSalario(string especialidad, int cantidad)
        {
            List<string> especialidades = await repo.GetEspecialidadesAsync();
            ViewData["Especialidades"] = especialidades;

            await repo.UpdateSalarioEspecialidadAsync(especialidad, cantidad);
            List<Doctor> doctores = await repo.GetDoctoresEspecialidadAsync(especialidad);
            return View(doctores);
        }

        [HttpPost]
        public async Task<IActionResult> SubirSalarioEF(string especialidad, int cantidad)
        {
            List<string> especialidades = await repo.GetEspecialidadesAsync();
            ViewData["Especialidades"] = especialidades;

            await repo.UpdateSalarioEspecialidadEF(especialidad, cantidad);
            List<Doctor> doctores = await repo.GetDoctoresEspecialidadAsync(especialidad);
            return View(doctores);
        }
    }
}

MvcCoreProceduresEF/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;

namespace MvcCoreProceduresEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreProceduresEF/Controllers/TrabajadoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class TrabajadoresController : Controller
    {
        private RepositoryEmpleados repo;

        public TrabajadoresController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<string> oficios = await repo.GetOficiosAsync();
            for (int i = 0; i < oficios.Count; ++i)
            {
                oficios[i] = oficios[i].ToUpper();
            }
            ViewData["Oficios"] = oficios;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string oficio)
        {
            TrabajadoresModel model = await repo.GetTrabajadoresModelOficioAsync(oficio);
            List<string> oficios = await repo.GetOficiosAsync();
            for (int i = 0; i < oficios.Count; ++i)
            {
                oficios[i] = oficios[i].ToUpper();
            }
            ViewData["Oficios"] = oficios;
            return View(model);
        }
    }
}

MvcCoreProceduresEF/Views/Empleados/Index.cshtml
@model List<VistaEmpleado>

<h1>Vista Empleados</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>APELLIDO</th>
            <th>OFICIO</th>
            <th>SALARIO</th>
            <th>DEPARTAMENTO</th>
            <th>LOCALIDAD</th>
        </tr>
    </thead>
    <tbody>
        @foreach(VistaEmpleado vista in Model)
        {
            <tr>
                <td>@vista.Id</td>
                <td>@vista.Apellido</td>
                <td>@vista.Oficio</td>
                <td>@vista.Salario</td>
                <td>@vista.Departamento</td>
                <td>@vista.Localidad</td>
            </tr>
        }
    </tbody>
</table>

MvcCoreProceduresEF/Views/Enfermos/Details.cshtml
@model Enfermo

<h1>Detalles del Enfermo</h1>
<h2>Apellido: @Model.Apellido</h2>
<h2>Direccion: @Model.Direccion</h2>
<h2>Fecha de nacimiento: @Model.FechaNac.ToShortDateString()</h2>
<h2>Sexo: @Model.Sexo</h2>
<h2>NSS: @Model.NSS</h2>

MvcCoreProceduresEF/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Enfermos</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Inscripcion</th>
            <th>Apellido</th>
            <th>Direccion</th>
            <th>Fecha Nacimiento</th>
            <th>Sexo</th>
            <th>NSS</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Enfermo enfermo in Model)
        {
            <tr>
                <td>@enfermo.Inscripcion</td>
                <td>@enfermo.Apellido</td>
                <td>@enfermo.Direccion</td>
                <td>@enfermo.FechaNac.ToShortDateString()</td>
                <td>@enfermo.Sexo</td>
                <td>@enfermo.NSS</td>
                <td><a asp-controller="Enfermos" asp-action="Details" asp-route-inscripcion="@enfermo.Inscripcion">Details</a></td>
                <td><a asp-controller="Enfermos" asp-action="Delete" asp-route-inscripcion="@enfermo.Inscripcion">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

MvcCoreProceduresEF/Views/Enfermos/Insert.cshtml
<h1>Insert Enfermo</h1>

<form method="post">
    <label>Apellido</label>
    <input type="text" name="apellido"/>
    <hr/>
    <label>Direccion</label>
    <input type="text" name="direccion"/>
    <hr/>
    <label>Sexo</label>
    <input type="text" name="sexo"/>
    <hr/>
    <label>Nss</label>
    <input type="text" name="nss"/>
    <hr/>
    <button>Insertar</button>
</form>

MvcCoreProceduresEF/Views/Enfermos/SubirSalario.cshtml
@model List<Doctor>

@{
    List<string> especialidades = ViewData["Especialidades"] as List<string>;
}

<h1>Subir salario por especialidad</h1>

<form method="post">
    <label>Especialidad</label>
    <select name="especialidad">
        <option>Selecciona una especialidad</option>
        @foreach (string especialidad in especialidades)
        {
            <option>@especialidad</option>
        }
    </select>
    <hr/>
    <label>Incremento</label>
    <input type="number" name="cantidad"/>
    <hr/>
    <button>Subir salario</button>
</form>

@if (Model != null)
{
    <table>
        <thead>
            <tr>
                <th>Hospital</th>
                <th>Doctor</th>
                <th>Especialidad</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Doctor doctor in Model)
            {
                <tr>
                    <td>@doctor.HospitalCod</td>
                    <td>@doctor.Apellido</td>
                    <td>@doctor.Especialidad</td>
                    <td>@doctor.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreProceduresEF/Views/Enfermos/SubirSalarioEF.cshtml
@{
    List<string> especialidades = ViewData["Especialidades"] as List<string>;
}

<h1>Subir salario por especialidad</h1>

<form method="post">
    <label>Especialidad</label>
    <select name="especialidad">
        <option>Selecciona una especialidad</option>
        @foreach (string especialidad in especialidades)
        {
            <option>@especialidad</option>
        }
    </select>
    <hr />
    <label>Incremento</label>
    <input type="number" name="cantidad" />
    <hr />
    <button>Subir salario</button>
</form>

@if (Model != null)
{
    <table>
        <thead>
            <tr>
                <th>Hospital</th>
                <th>Doctor</th>
                <th>Especialidad</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Doctor doctor in Model)
            {
                <tr>
                    <td>@doctor.HospitalCod</td>
                    <td>@doctor.Apellido</td>
                    <td>@doctor.Especialidad</td>
                    <td>@doctor.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreProceduresEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreProceduresEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreProceduresEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreProceduresEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreProceduresEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Insert">Insert Enfermo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="SubirSalario">Subir Salario Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="SubirSalarioEF">Subir Salario Doctores EF</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Vista Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trabajadores" asp-action="Index">Trabajadores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcCoreProceduresEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreProceduresEF/Views/Trabajadores/Index.cshtml
@model TrabajadoresModel

@{
    List<string> oficios = (List<string>) ViewData["Oficios"];
}

<form method="post">
    <label>Elige el oficio</label>
    <select name="oficio">
        <option>-- Elige un oficio --</option>
        @foreach(string oficio in oficios)
        {
            <option>@oficio</option>
        }
        </select>
        <button>Elegir</button>
</form>

@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Trabajadores</th>
                <th>Personas</th>
                <th>Suma</th>
                <th>Media</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Id Trabajador</th>
                                <th>Apellido</th>
                                <th>Oficio</th>
                                <th>Salario</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(Trabajador trabajador in Model.Trabajadores)
                            {
                                <tr>
                                    <td>@trabajador.IdTrabajador</td>
                                    <td>@trabajador.Apellido</td>
                                    <td>@trabajador.Oficio</td>
                                    <td>@trabajador.Salario</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
                <td>@Model.Personas</td>
                <td>@Model.Suma</td>
                <td>@Model.Media</td>
            </tr>
        </tbody>
    </table>
}